# Use an OpenJDK Runtime as a parent image
FROM openjdk:11
# Define environment variables
ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \JAVA_OPTS=""
# Set the working directory to /app
WORKDIR /todo-api
# Copy the executable into the container at /app
ADD target/*.jar todo.jar
# Make port 8080 available to the world outside this container
EXPOSE 8080
# Run app.jar when the container launches
RUN javac Main.java
CMD ["java", "-jar", "/todo.jar"]
